# Site Info
title: Kenshin
tagline: '吞风吻雨葬落日未曾彷徨 欺山赶海践雪径也未绝望'
description: 
baseurl: ""
url: http://kenshinsyrup.github.io

# Site configurations
gems: [jekyll-paginate]
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

# About/contact
author:
  name: Kenshin
  description: Kenshin's blog
  gravatar: 7f9673f1bc034bad53a37df330910b58 # md5 hash of your email address, you can get one in http://en.gravatar.com/
  contact:
    linkedin:  https://www.linkedin.com/in/zhao-wang-683b52127/
    github:    https://github.com/kenshinsyrup
    # facebook:  none
    # twitter:   none
    # weibo:     none
    # email:     kenshinsyrup@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/kenshinsyrup'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/skyrim.jpg

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-91673465-1' # leave blank if you don't want google analytics
disqus_short_name: 'kenshin' # leave blank if you don't want disqus