# Site Info
title: xy
tagline: '天阔阔雪漫漫共谁同航 这沙滚滚水皱皱笑着浪荡'
description: 
baseurl: ""
url: http://xy7313.github.io

# Site configurations
gems: [jekyll-paginate]
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

# About/contact
author:
  name: xy
  description: xy's blog
  gravatar: d4d8df06f6fa9dcbe4dc845db3c84a7c # md5 hash of your email address, you can get one in http://en.gravatar.com/
  contact:
    linkedin:  https://www.linkedin.com/in/xiaolu-yang
    github:    https://github.com/xy7313
    # facebook:  none
    # twitter:   none
    # weibo:     none
    # email:     path20110729@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - 'http://xy7313.github.io/about.html#/bored'
  Resume: 
    - 'http://xy7313.github.io/resume.html'
  Github Project: 
    - 'https://github.com/xy7313'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/background-cover.jpg

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-91673465-1' # leave blank if you don't want google analytics
disqus_short_name: 'xy' # leave blank if you don't want disqus