# Site settings
title: Xiaolu Yang's CV 
description: Xiaolu Yang's CV
favicon: /xy7313.github.io/assets/img/avatar.JPG
baseurl: http://xy7313.github.io/
url: http://xy7313.github.io/
rss_url: /resumecard/pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Xiaolu Yang
  title: Graduate Student
  address: Rutgers-New Brunswick
  email: path20110729@gmail.com
  link: https://github.com/xy7313
  weibo: xy7313
  github: xy7313
  linkedin: Xiaolu Yang
  twitter: 103393089
  gavatar: /xy7313.github.io/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Beyondsoft Technology Ltd
      location: BEIJING, CHINA
      title: Testing Engineer
      started: 2014
      duration: (2014 - 2015)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Beijing DaShengZhiXing Technology Ltd
      location: BEIJING, CHINA
      title: Consulting
      started: 2014
      duration: (2014 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Oracle (Intern(group work inside of college)
      location: TIANJIN, CHINA
      title: NETWROK Engineer(ENTRY LEVEL)
      started: 2013
      duration: (2013 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work4:
      company: Oracle (Intern(group work inside of college)
      location: TIANJIN, CHINA
      title: NETWROK Engineer(ENTRY LEVEL)
      started: 2013
      duration: (2013 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
 projectHistory:
    - work1:
      company: Beyondsoft Technology Ltd
      location: BEIJING, CHINA
      title: Testing Engineer
      started: 2014
      duration: (2014 - 2015)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Beijing DaShengZhiXing Technology Ltd
      location: BEIJING, CHINA
      title: Consulting
      started: 2014
      duration: (2014 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    
  educationHistory:
    - education1:
      organization: Tianjin Polytechnic University
      location: TIANJIN, CHINA
      degree: Bachelor
      major: Network Engineering
      started: 2005
      duration: (2010 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 80%
    - skill4:
      name: Java/Java EE
      percentage: 80%
    - skill5:
      name: Linux
      percentage: 80%
